// Generated by gencpp from file go_birds/AddTwoInts.msg
// DO NOT EDIT!


#ifndef GO_BIRDS_MESSAGE_ADDTWOINTS_H
#define GO_BIRDS_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <go_birds/AddTwoIntsRequest.h>
#include <go_birds/AddTwoIntsResponse.h>


namespace go_birds
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace go_birds


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::go_birds::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::go_birds::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::go_birds::AddTwoInts > {
  static const char* value()
  {
    return "go_birds/AddTwoInts";
  }

  static const char* value(const ::go_birds::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::go_birds::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::go_birds::AddTwoInts > 
template<>
struct MD5Sum< ::go_birds::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::go_birds::AddTwoInts >::value();
  }
  static const char* value(const ::go_birds::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::go_birds::AddTwoIntsRequest> should match 
// service_traits::DataType< ::go_birds::AddTwoInts > 
template<>
struct DataType< ::go_birds::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::go_birds::AddTwoInts >::value();
  }
  static const char* value(const ::go_birds::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::go_birds::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::go_birds::AddTwoInts > 
template<>
struct MD5Sum< ::go_birds::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::go_birds::AddTwoInts >::value();
  }
  static const char* value(const ::go_birds::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::go_birds::AddTwoIntsResponse> should match 
// service_traits::DataType< ::go_birds::AddTwoInts > 
template<>
struct DataType< ::go_birds::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::go_birds::AddTwoInts >::value();
  }
  static const char* value(const ::go_birds::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GO_BIRDS_MESSAGE_ADDTWOINTS_H
